### ISSUE TITLE
Linear system cannot be solved since matrix is singular  at _denseBackwardSubstitution 

### ISSUE THREAD

**Issue by nhammad** [MenesesGHZ/polynomial-regression-js#3]
I was trying to run the program here https://codesandbox.io/s/opur8?file=/src/PolynomialRegression.js

but after adding like 5-6 points when I increase the order/degree to around 4 or 5, I start seeing an error in the console log:
```
Error: Linear system cannot be solved since matrix is singular
    at _denseBackwardSubstitution (https://opur8.csb.app/node_modules/mathjs/lib/esm/function/algebra/solver/usolve.js:41:17)

    at Function.DenseMatrixArrayMatrix 
```
why is this so? After this error, there are no more changes in the graph even if we increase the degree.

**Comment by MenesesGHZ** [comment]
Sorry for the late response, I have been very busy. The issue that are you talking is more about the implementation that I made. Clearly there is the case where the matrix can be singular, which means `det(some_matrix) = 0` [(see more)](https://en.wikipedia.org/wiki/Invertible_matrix) the method implemented can not solve that.
